#Sem BioPython
dna = "AACTCCGTATCGGCTTAGCGCCTGACTTAACCACAGACCCGCCTTATGAGCTTCAACGGAAAGTATGTATCGGCCCCTTCCTATTTGATGTTAATCGCTACTTGGTATTGGCTGATTGCTTCCCTATTTATTTGAAGAGAAGTACCTGTTTCCTTGAAAGTTTGTATTCTTCCCATAAGTACCTTTTCCAAACTTACAGGACACCTCGTTGAATGGCCTAAGCCTAGCTGGCATACTAAGGCTAGTGTGTTAGGTTACAAGTTGGCTCCCTCCCGACGTAGCAGGCGGGTTGGTCTGAGCAGGTCAACCTCGTTCAGTGGCGATTTGAGAGCGAGGTTCTCTGACAAGCGCCCTTTGCCGTATCGTGGCCGCAAGGAGTTCCCGATATCGCGTTGAGTGTCGTAGGAGAGACTCGGAGCTAATGATGCACTTCCTGGGCACCATGGGGCAGCCCCCTTGGGTAACGCCGGAGCATAATAATATCCCCAAAGTAGCAGTGTATACGAATGGCTACGGTCGACATAGCATTATCAATTAAGTGATTTTATGTAAAAAGCGACCTTTTTTTGCCCTTGTACCCGGGCTGAGTCCTGTCGCGGCGGTGGGAGCCCCACTGTAGTCGGGGTTATGTGCTAGTACACCTAAAGTTAGATGGATGTCTAGTCCCTCCAACAATACCCCTAGCGCTGAGGTTCTTTGACTTCCTTTGATTTTTCAACCGAGCTTAATCACACAAACGGTCAGGATAAGTTATCAAACATTCCCTCGTGTAATTCCTCAACGCACTCGTCATACACGGATGGGCAGTACACGCAGCCCTGCGTCCGGCCACCTTGCAAGCCATGGGCGCATTCCCATGTGGAATTCCAGTGTAAGCACCACAGGCAGTGGTTTATATCCTATACCACTCTTGTTAGTGCGAACCTAGGTACGCGACAGCCTCGACCGAGGTCCCTATCACAACCGGAAATTTGCCGATGA"
dna_reverse_complement = str()
dna_reverse = dna [::-1]

for i in dna_reverse:
    if i=="A":
        dna_reverse_complement += "T"
    elif i=="T":
        dna_reverse_complement += "A"
    elif i=="C":
        dna_reverse_complement += "G"
    elif i=="G":
        dna_reverse_complement += "C"
    else:
        print("error")

print(dna_reverse_complement)

#ComBiopython
from Bio.Seq import Seq

dna = "ACATCAGCATGCATGCATGCATCGATCGATGCATCGATGCATCGATGCATGCATCGATCGATCGATCT"
dna = Seq(dna)
print(dna.reverse_complement())
